
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: vdt1410
    url: jdbc:sqlserver://DESKTOP-UOQ7755:1433;database=MobileApp;encrypt=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    database: sql_server
  thymeleaf:
    suffix: .html
  servlet:
    multipart:
      max-request-size: 20MB
logging:
  level:
    org:
      hibernate: info
  logback:
    rollingpolicy:
      max-file-size: 20MB

server:
  port: 8989

upload:
  path : classpath:/img/


